from __future__ import annotations

from typing import Final

CATEGORY_REVENUE_THIS_WEEK: Final[str] = "CATEGORY_REVENUE_THIS_WEEK"
SALES_TREND_BY_DAY_LAST_30: Final[str] = "SALES_TREND_BY_DAY_LAST_30"

PRODUCTS_SALES_REVENUE_OVERVIEW: Final[str] = "PRODUCTS_SALES_REVENUE_OVERVIEW"
PRODUCTS_SALES_COUNT_OVERVIEW: Final[str] = "PRODUCTS_SALES_COUNT_OVERVIEW"
REVENUE_WITHIN_TIMEFRAME: Final[str] = "REVENUE_WITHIN_TIMEFRAME"

